concert/concert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_prometheus import exports


urlpatterns = [
    path('', include('django_prometheus.urls')),
    path('admin/', admin.site.urls),
    path('ticketSales/', include('ticketSales.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/auth/', include('dj_rest_auth.urls')), # /login , /logout , /password/change , /password/reset , password/reset/confirm/
    path('api/auth/registration/', include('dj_rest_auth.registration.urls')), # /verify-email
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

concert/ticketSales/urls.py
from django.urls import path
from ticketSales import views

urlpatterns = [
    path('concert/list', views.concertListView),
    path('location/list', views.locationListView),
    path('concert/<int:concert_id>', views.concertDetailsView),
    path('time/list', views.timeView),
    path('concertEdit/<int:concert_id>', views.concertEditView),
    path('concert_list', views.concert_list),
    path('concert_details/<pk>', views.concert_details),
    path('concert_save', views.concert_save),
    path('concert_update/<pk>', views.concert_update),
    path('concert_delete/<pk>', views.concert_delete),
    path('location_list', views.location_list.as_view()),
    path('location_update/<pk>', views.location_update.as_view()),

]

concert/ticketSales/models.py
from django.db import models
from accounts.models import ProfileModel


class concertModel(models.Model):
    
    # class Meta:
    #     verbose_name = "کنسرت"
    #     verbose_name_plural = "کنسرت"
    
    Name = models.CharField(max_length=100)
    SingerName = models.CharField(max_length=100)
    lenght = models.IntegerField()
    Poster = models.ImageField(upload_to="concertImages/", null=True)
    
    def __str__(self):
        return self.SingerName
    
class locationModel(models.Model):
    IdNumber = models.IntegerField(primary_key=True)
    Name = models.CharField(max_length=100)
    Address = models.CharField(max_length=500, default="تهران-برج میلاد")
    Phone = models.CharField(max_length=11, null=True)
    capacity = models.IntegerField()
    
    def __str__(self):
        return self.Name
    
class timeModel(models.Model):
    concertModel = models.ForeignKey("concertModel", on_delete=models.PROTECT)  #first delete the time then the concert
    locationModel = models.ForeignKey("locationModel", on_delete=models.PROTECT)
    StartDateTime = models.DateTimeField()
    Seats = models.IntegerField()
    
    Start = 1
    End = 2
    Cancle = 3
    Sales = 4
    status_choices = ((Start,"فروش بلیط شروع شده است"),
                      (End,"فروش بلیط تمام شده است"),
                      (Cancle,"این سانس کنسل شده است"),
                      (Sales,"در حال فروش بلیط"))
    
    Status = models.IntegerField(choices=status_choices)
    
    def __str__(self):
        return "Time: {} ConcertName: {} Location: {}".format(self.StartDateTime, self.concertModel.Name, self.locationModel.Name)
    
     
class ticketModel(models.Model):
    ProfileModel = models.ForeignKey(ProfileModel, on_delete=models.PROTECT)
    timeModel = models.ForeignKey("timeModel", on_delete=models.PROTECT)
    ticketImage = models.ImageField(upload_to="ticketImages/")
    
    Name = models.CharField(max_length=100)
    Price = models.IntegerField()
    
    def __str__(self):
        return "TicketInfo: Profile:{} ConcertInfo:{} ".format(self.ProfileModel.__str__(), self.timeModel.__str__())

concert/ticketSales/forms.py
from django import forms
from ticketSales.models import concertModel

class SearchForm(forms.Form):
    SearchText = forms.CharField(max_length=100, label="نام کنسرت", required=False)
    
class ConcertForm(forms.ModelForm):
    class Meta:
        model = concertModel
        fields = ['Name', 'SingerName', 'lenght', 'Poster']

concert/ticketSales/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from ticketSales.models import concertModel, locationModel, timeModel
import ticketSales
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from ticketSales.forms import SearchForm, ConcertForm
import ticketSales.views
from .serializers import ConcertSerializer, LocationSerializer
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateAPIView
from .permissions import IsSuperUserOrReadOnly


#----------- api views ----------

class location_list(ListCreateAPIView):
    queryset = locationModel.objects.all()
    serializer_class = LocationSerializer
    permission_classes = ((IsSuperUserOrReadOnly,))
    
class location_update(RetrieveUpdateAPIView):
    queryset = locationModel.objects.all()
    serializer_class = LocationSerializer
    permission_classes = ((IsAdminUser,))

@api_view(["GET"])
@permission_classes((IsAuthenticated,))
def concert_list(request):
    concerts = concertModel.objects.all()
    concerts_serialize = ConcertSerializer(concerts, many=True)
    return Response(concerts_serialize.data)

@api_view(["GET"])
def concert_details(request, pk):
    concert = concertModel.objects.get(id=pk)
    concert_serialize = ConcertSerializer(concert, many=False)
    return Response(concert_serialize.data)

@api_view(["POST"])
def concert_save(request):
    concert =ConcertSerializer(data=request.data)
    if concert.is_valid():
        concert.save()

    return Response(concert.data)

@api_view(["POST"])
def concert_update(request, pk):
    instance = concertModel.objects.get(id=pk)
    concert = ConcertSerializer(instance=instance,data=request.data)
    if concert.is_valid():
        concert.save()

    return Response(concert.data)

@api_view(["DELETE"])
def concert_delete(request, pk):
    instance = concertModel.objects.get(id=pk)
    instance.delete()

    return Response("concert deleted!")


#----------- ui views ----------

def concertListView(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        SearchText = searchForm.cleaned_data["SearchText"]
        concerts = concertModel.objects.filter(Name__contains=SearchText)
    else:
        concerts = concertModel.objects.all()
    
    context = {
        "concertlist": concerts,
        "concertcount": concerts.count(),
        "searchForm": searchForm
    }
    
    return render(request, "ticketSales/concertlist.html", context)

@login_required
def locationListView(request):
    locations = locationModel.objects.all()
    context = {
        "locationlist": locations,
    }
    
    return render(request, "ticketSales/locationlist.html", context)

def concertDetailsView(request, concert_id):
    concert = concertModel.objects.get(pk=concert_id)
    
    context = {
        "concertdetails": concert
    }
    
    return render(request, "ticketSales/concertDetails.html", context)

@login_required
def timeView(request):
    # if request.user.is_authenticated and request.user.is_active:
        times = timeModel.objects.all()
        context = {
            "timelist": times,
        }
        
        return render(request, "ticketSales/timeList.html", context)
    # else:
    #     return HttpResponseRedirect(reverse(accounts.views.loginView))

def concertEditView(request, concert_id):
    concert = concertModel.objects.get(pk=concert_id)

    if request.method == "POST":
        concertForm = ConcertForm(request.POST, request.FILES, instance=concert)
        if concertForm.is_valid:
            concertForm.save()
            return HttpResponseRedirect(reverse(ticketSales.views.concertListView))
    else:
            concertForm = ConcertForm(instance=concert)
            
    context = {
            "concertForm": concertForm,
            "PosterImage": concert.Poster
        }
        
    return render(request, "ticketSales/concertEdit.html", context)

concert/ticketSales/templates/ticketSales/concertDetails.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %}
    جزئیات {{ concertdetails.Name }}
{% endblock %}

{% block mainContent %}

    <div class="col-mid-10">
        <h3>نام کنسرت : {{ concertdetails.Name }}</h3>
        <h3>خواننده کنسرت : {{ concertdetails.SingerName }}</h3>
        <h3>مدت زمان کنسرت : {{ concertdetails.lenght }}</h3>
    </div>
    <div class="col-mid-2">
        <div class="imageBox">
            <img src="{{ concertdetails.Poster.url }}">
        </div>
        <a href="/ticketSales/concertEdit/{{ concertdetails.id }}" class="btn btn-success">ویرایش</a>
    </div>
{% endblock %}

concert/ticketSales/templates/ticketSales/concertEdit.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
     ویرایش کنسرت 
{% endblock%}

{% block mainContent %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ concertForm }} -->
        <div class="mainborder">
            <div class="row">
                <div class="col-md-6">
                    <p class="mylable">Name: {{ concertForm.Name }}</p>
                    <p class="mylable">SingerName: {{ concertForm.SingerName }}</p>
                    <p class="mylable">lenght: {{ concertForm.lenght }}</p>
                </div>
                <div  class="col-md-6">
                   <div class="imageBox">
                       <img src="{{ PosterImage.url }}">
                   </div>
                    {{ concertForm.Poster }}
                </div>
            </div>
        </div>
        <div class="bottonborder">
            <button type="submit" class="btn btn-success">ذخیره</button>
        </div>
    </form>
{% endblock%}
               

concert/ticketSales/templates/ticketSales/concertlist.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %}
    لیست کنسرت ها
{% endblock %}
{% block mainContent %}
    {% if concertlist %}
        <form action="" method="GET">
            {{ searchForm }}
            <button type="submit" class="btn btn-success">جستجو</button>
        </form>
        {% for concert in concertlist  %}
            <div class="col-md-2">
                <a href="/ticketSales/concert/{{ concert.id }}">
                    <div class="imageBox">
                        <img src="{{ concert.Poster.url }}">
                            {{ concert }}
                    </div>
                </a>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

concert/ticketSales/templates/ticketSales/layout.html
{% load static %}
<!DOCTYPE html>
    <html dir="rtl">
        <head>
            <title>سامانه فروش بلیط کنسرت</title>
            <link rel="stylesheet" type="text/css" href="{% static '/ticketSales/css/bootstrap.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static '/ticketSales/css/fontawesome.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static '/ticketSales/css/style.css' %}">
        </head>
        <body>
            <div class="container">
                <div class="row box">
                    <h1>{% block titlepage %} {% endblock %}</h1>
                    <ul class="btnul">
                        {% if user.is_authenticated %}
                            <li><a class="btn btn-success" href="/accounts/profile">پروفایل</a></li>
                            <li><a class="btn btn-danger" href="/accounts/logout">خروج</a></li>
                        {% else %}
                            <li><a class="btn btn-success" href="/accounts/login">ورود</a></li>
                            <li><a class="btn btn-danger" href="/accounts/profileRegister">ثبت نام</a></li>
                        {% endif %}
                        <li><a class="btn default" href="/ticketSales/concert/list">صفحه اصلی</a></li>
                        <li><a class="btn btn-primary" href="/ticketSales/time/list">مشاهده ی سانس های کنسرت</a></li>
                        <li><a class="btn btn-danger" href="/ticketSales/location/list">اطلاعات محل</a></li>
                    </ul>
                </div>
                <div class="row">

                        {% block mainContent %}{% endblock %}

                </div>
            </div>
        </body>
        <script src="{% static "ticketSales/js/jquery-3.7.1.min.js" %}"></script>
        <script src="{% static "ticketSales/js/bootstrap.bundle.js" %}"></script>
        <script src="{% static "ticketSales/js/fontawesome.js" %}"></script>
        <script src="{% static "ticketSales/js/main.js" %}"></script>
    </html>

concert/ticketSales/templates/ticketSales/locationList.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    لیست مکان های برگزاری کنسرت 
{% endblock%}

{% block mainContent %}

    <div class="row locationHeader">
        <div class="col-md-3">
            <h3>نام سالن</h3>
        </div>
        <div class="col-md-9">
        <h3>آدرس</h3>
        </div>
    </div>

    {% if locationlist %}
        {% for location in locationlist %}
          
            <div class="row location">
                <div class="col-md-3">
                    {{ location.Name }}
                </div>
                <div class="col-md-9">
                    {{ location.Address }}
                </div>
               
            </div>
           
        {% endfor %}
    {% endif %}

{% endblock%}

concert/ticketSales/templates/ticketSales/timeList.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    لیست سانس ها
{% endblock%}

{% block mainContent %}
    {% if timelist %}
        {% for time in timelist %}
            <div class="col-md-2">
                <a>
                    <div class="timeBox">
                       <h2> {{ time.concertModel.Name  }}</h2>
                       <p>{{ time.concertModel.SingerName  }}</p>
                       <p>{{ time.locationModel.Name  }}</p>
                       <p>{{ time.get_jalai_date }}</p>
                       <div 
                       
                        class="
                        
                        {% if time.Status == time.Start %}
                            btn btn-success

                        {% elif  time.Status == time.End %}
                            btn btn-danger

                         {% elif  time.Status == time.Cancle %}
                            btn default

                        {% elif  time.Status == time.Sales %}
                            btn btn-primary

                        {% endif %}
                        
                        ">

                           {{ time.get_Status_display}}
                       </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    {% endif %}

{% endblock%}
               